apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: customclass
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  local:
    path: /mnt/data
